### ISSUE TITLE
Connection Approach

### ISSUE THREAD

**Issue by xerxel** [el-dockerr/Unreal-Kafka#1]
This module is great. However, how to enter connection details, when using a connection string, if the only inputs are Servers, UserName and Password?

For example, here is my normal connection string:

Endpoint=sb://kafkaserver.servicebus.windows.net/;SharedAccessKeyName=policy01;SharedAccessKey=4eXfe8cJcOGVd+AEhPxP9Bo=;EntityPath=eventhubinstancename

Does it support it?

**Comment by el-dockerr** [comment]
It only support user/password actually. But I'll leave this as unsolved here to implement it.
Please bear with me - it will take some time.

**Comment by xerxel** [comment]
Thank you! I will see if Aider can help me implement it too. If it works, I will share code.

**Comment by xerxel** [comment]
I have news! Azure Event Hubs support many protocols. But the protocol being used here is only Kafka raw protocol. Therefore, to make this compatible with Azure event hubs, use the following values:

Servers = _mynamespace_.servicebus.windows.net:9093
Username = $ConnectionString
Password = Endpoint=sb://_mynamespace_.servicebus.windows.net/;SharedAccessKeyName=_policy01_;SharedAccessKey=_sdfsdfsdfsdfsdfdsfsdfsdfsdfsdfdsf+AEhPxP9Bo=_;EntityPath=_topic-name_

The password is the entire connection string starting with "Endpoint="

Replace the parts in italic with your own values. For more information see: [Connectionstring](https://learn.microsoft.com/en-us/azure/event-hubs/event-hubs-quickstart-kafka-enabled-event-hubs?tabs=connection-string)

You can also get this value from the Shared Access Policy blade in Azure on the Event Hubs Instance page. The only thing I have not worked out is which Consumer Group it is reading from.

Thank you so much to @el-dockerr for creating this! :-)

**Comment by el-dockerr** [comment]
I'm happy you like this.
Anyways - I'll will fix this a bit and make it easier for Azure Users
